<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Monitor.Api</RootNamespace>
    <AssemblyName>Monitor.Api</AssemblyName>
    <UserSecretsId>monitor-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Monitor.Core\Monitor.Core.csproj" />
  </ItemGroup>

</Project>
